services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Thw\ThwOvssp\:
    resource: '../Classes/*'

  Thw\ThwOvssp\Command\ImportCommand:
    tags:
      - name: console.command
        command: 'ovssp:import'
        description: 'Import CSV data (users, orgunits, directories)'
