services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Init\Thw\Ovssp\:
    resource: '../Classes/*'

  Init\Thw\Ovssp\Command\ImportCommand:
    tags:
      - name: console.command
        command: 'ovssp:import'
        description: 'Import CSV data (users, orgunits, directories)'
